#!/usr/bin/bash


if [ "$1" = "prod" ]; then
    ENDPOINT_URL=""  # Leave empty for production
else
    ENDPOINT_URL="--endpoint-url=http://localhost:8000"
fi

aws dynamodb delete-table $ENDPOINT_URL \
--query "TableNames[]" \
--output table 
