#!/usr/bin/env python3

import boto3 
import sys

attrs = {
    'endpoint_url': 'http://localhost:8000'
    }

if len(sys.argv) == 2:
    if "prod" in sys.argsv[1]:
        attrs = {}

ddb = boto3.client('dynamob', **attrs)
table_name = 'cruddur-message'

response = ddb.create_table(
    Tablename=table_name,
    AttributeDefinitions=[
        {
            'AttributeName': 'pk',
            'AttributeType': 'S'
        }, 
        {
            'AttributeName': 'sk',
            'AttributeType': 'S'
        },                             
   ],

    KeySchema=[
        {
            'AttributeName': 'pk'
            'KeyType': 'HASH'
        },
        {
            'AttributeName': 'sk'
            'KeyType': 'RANGE'
        },
    ],
   #GlobalSecondaryIndexes=[],
    BillingMode='PROVISIONED',
    ProvisionedThroughput={
        'ReadCapacityUnits': 5,
        'WriteCapacityUnits': 5
    }
)

print(response)